baseURL = 'https://portfolio-pq22.onrender.com/'
languageCode = 'en-us'
title = 'James Medd'
theme = "jmcv"
[params]
  subtitle = 'Digital Experience Designer'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
